### ISSUE TITLE
MMM-GPIO-Notifications not registering button press

### ISSUE THREAD

**Issue by threesquare** [Tom-Hirschberger/MMM-GPIO-Notifications#38]
I want to use MMM-GPIO-Notifications to send notifications to MMM-Carousel to initiate page change. I can't seem to get it working at all.

buttons are connected and registered using a simple button test script.
GPIOinfo shows the correct pins
```
	line  17:     "GPIO17" "opengpio_0_17_watch" input active-high [used]
	line  27:     "GPIO27" "opengpio_0_27_watch" input active-high [used]
```
my config.js
```
    {
        module: 'MMM-GPIO-Notifications',
        config: {
            '17': {
              delay: 0,
              notifications_high: [
                {
                  notification: 'CAROUSEL_NEXT',
                  payload: null
                },
              ]
            },
            '27': {
              delay: 0,
              notifications_high: [
                {
                  notification: 'CAROUSEL_PREVIOUS',
                  payload: null
                }
              ]
            }
        }
    },
```
 that simple button test script shows GPIO busy when MM is running with the MMM-GPIO-Notifications activated. which I think is the expected behavior. If I stop MM from running, the test script loads and shows the button press.
```
pi@magicmirror:~ $ python buttons.py
Traceback (most recent call last):
  File "/home/pi/buttons.py", line 9, in <module>
    GPIO.setup(BUTTON_GPIO, GPIO.IN, pull_up_down=GPIO.PUD_UP)  # Use internal pull-up resistor
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/RPi/GPIO/__init__.py", line 696, in setup
    _check(lgpio.gpio_claim_input(_chip, gpio, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lgpio.py", line 755, in gpio_claim_input
    return _u2i(_lgpio._gpio_claim_input(handle&0xffff, lFlags, gpio))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lgpio.py", line 458, in _u2i
    raise error(error_text(v))
lgpio.error: 'GPIO busy'
```
I also have OnOff installed in the MagicMirror directory
The weird part is that I did managed to get MMM-GPIO-Notifications working with the button presses initially, then after a reboot it stopped working completely.
More than happy to provide any additional info/logs. Not 100% proficient in this, so please bear with me. thanks!

**Comment by Tom-Hirschberger** [comment]
Hi,

i just took a look at the code of [MMM-Carousel](https://github.com/barnabycolby/MMM-Carousel) to check if the module accepts `null` in the payload of the notifications.
But the module does not listen for any notifications at all. So do you use any other version of MMM-Carousel and did you ever test if `CAROUSEL_NEXT` changes to a different view?

If you started MagicMirror by pm2 you will find your log files in `/home/pi/.pm2/logs`. 

There is one file for errors called `MagicMirror-error.log` and one for normal logs called `MagicMirror-out.log`.
Is there anything relevant in the logs related to this module?

You will not be able to run your test script and my module at the same time. The access to GPIO is exclusive to one job since about one year.

**Comment by Tom-Hirschberger** [comment]
Just found this fork of MMM-Carousel https://github.com/shbatm/MMM-Carousel

If you use this fork the `null` payload should not be a problem.

**Comment by threesquare** [comment]
yes, sorry I should have been more specific. I am using that fork. I am able to send notifications and initiate the slide change via MMM-RemoteControl. so that isolated the issue with that Carousel fork.
I'm looking through the logs and I'm not seeing any error relating to MMM-GPIO-Notifications.

the console log shows everything is loaded
```
[Log] Load script: modules/MMM-GPIO-Notifications/MMM-GPIO-Notifications.js (loader.js, line 178)
[Log] Module registered: MMM-GPIO-Notifications (module.js, line 489)
[Info] Bootstrapping module: MMM-GPIO-Notifications (loader.js, line 151)
[Log] Scripts loaded for: MMM-GPIO-Notifications (loader.js, line 155)
[Log] Styles loaded for: MMM-GPIO-Notifications (loader.js, line 158)
[Log] Translations loaded for: MMM-GPIO-Notifications (loader.js, line 161)
[Log] Load script: modules/MMM-Carousel/MMM-Carousel.js (loader.js, line 178)
[Log] Check MagicMirror² version for module 'MMM-Carousel' - Minimum version:  2.3.0 - Current version: 2.29.0 (module.js, line 481)
[Log] Version is ok! (module.js, line 483)
[Log] Module registered: MMM-Carousel (module.js, line 489)
[Info] Bootstrapping module: MMM-Carousel (loader.js, line 151)
[Log] Scripts loaded for: MMM-Carousel (loader.js, line 155)
[Log] Load stylesheet: modules/MMM-Carousel/MMM-Carousel.css (loader.js, line 194)
[Log] Styles loaded for: MMM-Carousel (loader.js, line 158)
[Log] Translations loaded for: MMM-Carousel (loader.js, line 161)
```
MagicMirror-out.log
```
Module helper loaded: MMM-GPIO-Notifications
Connecting socket for: MMM-GPIO-Notifications 
[2024-11-18 13:45:05.994] [LOG]   MMM-GPIO-Notifications: Using naming schema Default 
[2024-11-18 13:45:05.999] [LOG]   Using naming schema of RaspberryPi_4B! 
[2024-11-18 13:45:06.000] [LOG]   MMM-GPIO-Notifications: Trying to registering pin: 17 
[2024-11-18 13:45:06.003] [LOG]   MMM-GPIO-Notifications: Using chip (0) and line (17) info of GPIO17 
[2024-11-18 13:45:06.005] [LOG]   MMM-GPIO-Notifications: Watched pin: 17 has low state delay of 0! 
[2024-11-18 13:45:06.007] [LOG]   MMM-GPIO-Notifications: Watched pin: 17 has high state delay of 0! 
[2024-11-18 13:45:06.014] [LOG]   MMM-GPIO-Notifications: Successfully registered pin: 17 
[2024-11-18 13:45:06.015] [LOG]   MMM-GPIO-Notifications: Trying to registering pin: 27 
[2024-11-18 13:45:06.017] [LOG]   MMM-GPIO-Notifications: Using chip (0) and line (27) info of GPIO27 
[2024-11-18 13:45:06.018] [LOG]   MMM-GPIO-Notifications: Watched pin: 27 has low state delay of 0! 
[2024-11-18 13:45:06.020] [LOG]   MMM-GPIO-Notifications: Watched pin: 27 has high state delay of 0! 
[2024-11-18 13:45:06.025] [LOG]   MMM-GPIO-Notifications: Successfully registered pin: 27 
[2024-11-18 13:45:49.956] [LOG]   MMM-GPIO-Notifications: Watched pin: 27 triggered with value 0! 
[2024-11-18 13:45:49.958] [LOG]   MMM-GPIO-Notifications: Sending notifications of pin 27... 
[2024-11-18 13:45:49.959] [LOG]   MMM-GPIO-Notifications: Skipped notifications of pin 27 cause the state 0 has no notifications configured. 
[2024-11-18 13:45:49.964] [LOG]   Falling Event false 
[2024-11-18 13:45:49.967] [LOG]   MMM-GPIO-Notifications: Watched pin: 27 triggered with value 0! 
[2024-11-18 13:45:49.979] [LOG]   MMM-GPIO-Notifications: Sending notifications of pin 27... 
[2024-11-18 13:45:49.986] [LOG]   MMM-GPIO-Notifications: Skipped notifications of pin 27 cause the state 0 has no notifications configured. 
[2024-11-18 13:45:50.066] [LOG]   Rising Event true 
[2024-11-18 13:45:50.069] [LOG]   MMM-GPIO-Notifications: Watched pin: 27 triggered with value 1! 
[2024-11-18 13:45:50.071] [LOG]   MMM-GPIO-Notifications: Sending notifications of pin 27... 
[2024-11-18 13:45:50.073] [LOG]   MMM-GPIO-Notifications: Sending notifications for high state of pin 27... 
[2024-11-18 13:45:54.352] [LOG]   Falling Event false 
[2024-11-18 13:45:54.358] [LOG]   MMM-GPIO-Notifications: Watched pin: 17 triggered with value 0! 
[2024-11-18 13:45:54.363] [LOG]   MMM-GPIO-Notifications: Sending notifications of pin 17... 
[2024-11-18 13:45:54.364] [LOG]   MMM-GPIO-Notifications: Skipped notifications of pin 17 cause the state 0 has no notifications configured. 
[2024-11-18 13:45:54.741] [LOG]   Rising Event true 
[2024-11-18 13:45:54.743] [LOG]   MMM-GPIO-Notifications: Watched pin: 17 triggered with value 1! 
[2024-11-18 13:45:54.744] [LOG]   MMM-GPIO-Notifications: Sending notifications of pin 17... 
[2024-11-18 13:45:54.747] [LOG]   MMM-GPIO-Notifications: Sending notifications for high state of pin 17... 
[2024-11-18 13:45:57.507] [LOG]   Falling Event false 
[2024-11-18 13:45:57.517] [LOG]   MMM-GPIO-Notifications: Watched pin: 17 triggered with value 0! 
[2024-11-18 13:45:57.519] [LOG]   MMM-GPIO-Notifications: Sending notifications of pin 17... 
[2024-11-18 13:45:57.530] [LOG]   MMM-GPIO-Notifications: Skipped notifications of pin 17 cause the state 0 has no notifications configured. 
[2024-11-18 13:45:57.909] [LOG]   Rising Event true 
[2024-11-18 13:45:57.910] [LOG]   MMM-GPIO-Notifications: Watched pin: 17 triggered with value 1! 
[2024-11-18 13:45:57.916] [LOG]   MMM-GPIO-Notifications: Sending notifications of pin 17... 
[2024-11-18 13:45:57.917] [LOG]   MMM-GPIO-Notifications: Sending notifications for high state of pin 17... 
[2024-11-18 13:46:01.135] [LOG]   Falling Event false 
[2024-11-18 13:46:01.140] [LOG]   MMM-GPIO-Notifications: Watched pin: 17 triggered with value 0! 
[2024-11-18 13:46:01.141] [LOG]   MMM-GPIO-Notifications: Sending notifications of pin 17... 
[2024-11-18 13:46:01.142] [LOG]   MMM-GPIO-Notifications: Skipped notifications of pin 17 cause the state 0 has no notifications configured. 
```

there isn't anything relevant in the error.log

**Comment by Tom-Hirschberger** [comment]
Hi,

two things...
I would add a small delay of about 200ms to the buttons as it looks like at least the one connected to pin 17 bounces a little bit.
And i am still unsure if null as a value will work at the moment. As Carousel accepts any payload for this notifications i think it is worth to try some other payload value.

```json
    {
        module: 'MMM-GPIO-Notifications',
        config: {
            '17': {
              delay: 200,
              notifications_high: [
                {
                  notification: 'CAROUSEL_NEXT',
                  payload: true
                },
              ]
            },
            '27': {
              delay: 200,
              notifications_high: [
                {
                  notification: 'CAROUSEL_PREVIOUS',
                  payload: true
                }
              ]
            }
        }
    },
```

All other things look good to me. The pins get registered correctly and the events are captured.

**Comment by Tom-Hirschberger** [comment]
Did you make any progress with your problem?

**Comment by Tom-Hirschberger** [comment]
As I did not get any update I will close the ticket for now. Feel free to re-open it if the problem still exists
